### ISSUE TITLE
Does not migrate all files, error exit code 128, related to gitignore file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [trevorr/vss2git#10]
```
What steps will reproduce the problem?
1. Enter VSS repository location and local directory location and click on GO


What is the expected output? What do you see instead?

Whole repository is not migrated. I tried many times. I  get one error message 
which says "the following path are ignored by one one of your gitignore file. 
Use -f if you really want to add them. 

What version of the product are you using? On what operating system?
I am using 1.0.10.0 on windows 7 enterprise edition.

Please provide any additional information below.


```

Original issue reported on code.google.com by `tulikagu...@gmail.com` on 13 Aug 2014 at 7:51

Attachments:
- [giterror.png](https://storage.googleapis.com/google-code-attachments/vss2git/issue-10/comment-0/giterror.png)

**Comment by wqweto** [comment]
I have a similar problem because there obviously is a `.gitignore` file in a folder in the source VSS repository.

Here is a dump of the releveant part of `Vss2Git.log`

```
...
Executing: C:\Program Files\Git\cmd\git.exe add -- C:\Git\Dreem\Src\NMAKE.EXE
!The following paths are ignored by one of your .gitignore files:
!Src/NMAKE.EXE
!Use -f if you really want to add them.
ERROR: git returned exit code 1
Executable: C:\Program Files\Git\cmd\git.exe
Arguments: add -- C:\Git\Dreem\Src\NMAKE.EXE
Stdout: 
Stderr: The following paths are ignored by one of your .gitignore files:
Src/NMAKE.EXE
Use -f if you really want to add them.
Hpdi.Vss2Git.ProcessExitException: git returned exit code 1
   at Hpdi.Vss2Git.GitWrapper.FailExitCode(String exec, String args, String stdout, String stderr, Int32 exitCode) in C:\Work\Temp\vss2git\Vss2Git\GitWrapper.cs:line 301
   at Hpdi.Vss2Git.GitWrapper.ExecuteUnless(ProcessStartInfo startInfo, String unless) in C:\Work\Temp\vss2git\Vss2Git\GitWrapper.cs:line 293
   at Hpdi.Vss2Git.GitWrapper.Add(String path) in C:\Work\Temp\vss2git\Vss2Git\GitWrapper.cs:line 110
   at Hpdi.Vss2Git.GitExporter.WriteRevision(VssPathMapper pathMapper, VssActionType actionType, String physicalName, Int32 version, String underProject, GitWrapper git) in C:\Work\Temp\vss2git\Vss2Git\GitExporter.cs:line 656
   at Hpdi.Vss2Git.GitExporter.ReplayRevision(VssPathMapper pathMapper, Revision revision, GitWrapper git, LinkedList`1 labels) in C:\Work\Temp\vss2git\Vss2Git\GitExporter.cs:line 523
   at Hpdi.Vss2Git.GitExporter.<>c__DisplayClass20_1.<ReplayChangeset>b__0() in C:\Work\Temp\vss2git\Vss2Git\GitExporter.cs:line 247
   at Hpdi.Vss2Git.GitExporter.AbortRetryIgnore(ThreadStart work, MessageBoxButtons buttons) in C:\Work\Temp\vss2git\Vss2Git\GitExporter.cs:line 593
```

**Comment by dimitar-grigorov** [comment]
The issue is that git refuses to add files matching patterns in a .gitignore thats already committed from VSS. My fork https://github.com/dimitar-grigorov/vss2git has two alternative backends (LibGit2Sharp and FastImport) that don't use git.exe at all, so this kind of problem doesn't come up.
