### ISSUE TITLE
git was told to rm a directory which had uncommitted files in it.

### ISSUE THREAD

**Issue by Ma-XX-oN** [trevorr/vss2git#21]
This is pretty good, one bug I found though is that somehow that git was told to delete a directory which has uncommitted files in it.  Here is part of the log:

	d:\Users\maxxon\Desktop\vss2git\Time and Billings\Synchronize Process Setup: Delete Media
	Executing: C:\Program Files\Git\cmd\git.exe rm -r -- "d:\Users\maxxon\Desktop\vss2git\Time and Billings\Synchronize Process Setup\Media"
	!error: the following files have changes staged in the index:
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Default.mda
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/DATA.TAG
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/SETUP.EXE
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/SETUP.INI
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_INST32I.EX_
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_ISDEL.EXE
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_setup.dll
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_sys1.cab
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_user1.cab
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/data1.cab
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/lang.dat
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/layout.bin
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/os.dat
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/setup.bmp
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/setup.ins
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/setup.lid
	!    Time and Billings/Synchronize Process Setup/Media/Media/Default/Report Files/5-10-1999 11.26.59AM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/DATA.TAG
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/SETUP.EXE
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/SETUP.INI
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_INST32I.EX_
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_ISDEL.EXE
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_setup.dll
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_sys1.cab
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_user1.cab
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/data1.cab
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/lang.dat
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/layout.bin
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/os.dat
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/setup.ins
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/setup.lid
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 1.01.50PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 1.53.41PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 11.33.19AM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 2.08.46PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 2.45.54PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.04.32PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.05.42PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.08.33PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.08.58PM.log
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 1.01.51PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 1.53.43PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 11.33.20AM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 2.08.48PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 2.45.55PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.04.33PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.05.43PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.08.34PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.08.59PM.rpt
	!    Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/default.mda
	!(use --cached to keep the file, or -f to force removal)
	ERROR: git returned exit code 1
	Executable: C:\Program Files\Git\cmd\git.exe
	Arguments: rm -r -- "d:\Users\maxxon\Desktop\vss2git\Time and Billings\Synchronize Process Setup\Media"
	Stdout:
	Stderr: error: the following files have changes staged in the index:
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Default.mda
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/DATA.TAG
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/SETUP.EXE
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/SETUP.INI
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_INST32I.EX_
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_ISDEL.EXE
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_setup.dll
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_sys1.cab
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/_user1.cab
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/data1.cab
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/lang.dat
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/layout.bin
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/os.dat
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/setup.bmp
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/setup.ins
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Disk Images/disk1/setup.lid
		Time and Billings/Synchronize Process Setup/Media/Media/Default/Report Files/5-10-1999 11.26.59AM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/DATA.TAG
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/SETUP.EXE
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/SETUP.INI
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_INST32I.EX_
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_ISDEL.EXE
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_setup.dll
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_sys1.cab
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/_user1.cab
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/data1.cab
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/lang.dat
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/layout.bin
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/os.dat
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/setup.ins
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Disk Images/disk1/setup.lid
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 1.01.50PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 1.53.41PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 11.33.19AM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 2.08.46PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 2.45.54PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.04.32PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.05.42PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.08.33PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Log Files/5-10-1999 3.08.58PM.log
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 1.01.51PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 1.53.43PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 11.33.20AM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 2.08.48PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 2.45.55PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.04.33PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.05.43PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.08.34PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/Report Files/5-10-1999 3.08.59PM.rpt
		Time and Billings/Synchronize Process Setup/Media/Media/Synchronize Process/default.mda
	(use --cached to keep the file, or -f to force removal)
	Hpdi.Vss2Git.ProcessExitException: git returned exit code 1
	   at Hpdi.Vss2Git.GitWrapper.FailExitCode(String exec, String args, String stdout, String stderr, Int32 exitCode) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:lin
	e 301
	   at Hpdi.Vss2Git.GitWrapper.ExecuteUnless(ProcessStartInfo startInfo, String unless) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 296
	   at Hpdi.Vss2Git.GitWrapper.GitExec(String args) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 263
	   at Hpdi.Vss2Git.GitWrapper.Remove(String path, Boolean recursive) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 139
	   at Hpdi.Vss2Git.GitExporter.ReplayRevision(VssPathMapper pathMapper, Revision revision, GitWrapper git, LinkedList`1 labels) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 327
	   at Hpdi.Vss2Git.GitExporter.<>c__DisplayClass11.<ReplayChangeset>b__d() in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 247
	   at Hpdi.Vss2Git.GitExporter.AbortRetryIgnore(ThreadStart work, MessageBoxButtons buttons) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 594

Not sure what caused this but if you want, I could help you figure it out.  I'll keep the logs for a while.  I forced the deletion of the directory as the info it was dealing with isn't all that critical to me, but it might be nice to find out what happened.

Maxx

**Comment by Ma-XX-oN** [comment]
This happened again, this time I just committed the files and continued.
