### ISSUE TITLE
git was told to move a file, but the file already exists

### ISSUE THREAD

**Issue by Ma-XX-oN** [trevorr/vss2git#22]
Still going through the repository and found another issue, where a file is attempted to be moved, but it already exists.  Here is part of the log:

	Replaying changeset 45064 from 01/04/2002 16:33:02
	d:\Users\maxxon\Desktop\vss2git\CaseWare\4.3\Cwin32\cwmfc: Rename CoolTree.cpp to cwuitree.cpp
	Executing: C:\Program Files\Git\cmd\git.exe mv -- d:\Users\maxxon\Desktop\vss2git\CaseWare\4.3\Cwin32\cwmfc\CoolTree.cpp d:\Users\maxxon\Desktop\vss2git\CaseWare\4.3\Cwin32\cwmfc\cwuitree.cpp
	!fatal: destination exists, source=CaseWare/4.3/Cwin32/cwmfc/CoolTree.cpp, destination=CaseWare/4.3/Cwin32/cwmfc/cwuitree.cpp
	ERROR: git returned exit code 128
	Executable: C:\Program Files\Git\cmd\git.exe
	Arguments: mv -- d:\Users\maxxon\Desktop\vss2git\CaseWare\4.3\Cwin32\cwmfc\CoolTree.cpp d:\Users\maxxon\Desktop\vss2git\CaseWare\4.3\Cwin32\cwmfc\cwuitree.cpp
	Stdout:
	Stderr: fatal: destination exists, source=CaseWare/4.3/Cwin32/cwmfc/CoolTree.cpp, destination=CaseWare/4.3/Cwin32/cwmfc/cwuitree.cpp
	Hpdi.Vss2Git.ProcessExitException: git returned exit code 128
	   at Hpdi.Vss2Git.GitWrapper.FailExitCode(String exec, String args, String stdout, String stderr, Int32 exitCode) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 301
	   at Hpdi.Vss2Git.GitWrapper.ExecuteUnless(ProcessStartInfo startInfo, String unless) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 296
	   at Hpdi.Vss2Git.GitWrapper.GitExec(String args) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 263
	   at Hpdi.Vss2Git.GitWrapper.Move(String sourcePath, String destPath) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 144
	   at Hpdi.Vss2Git.GitExporter.CaseSensitiveRename(String sourcePath, String destPath, RenameDelegate renamer) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 752
	   at Hpdi.Vss2Git.GitExporter.ReplayRevision(VssPathMapper pathMapper, Revision revision, GitWrapper git, LinkedList`1 labels) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 375
	   at Hpdi.Vss2Git.GitExporter.<>c__DisplayClass11.<ReplayChangeset>b__d() in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 247
	   at Hpdi.Vss2Git.GitExporter.AbortRetryIgnore(ThreadStart work, MessageBoxButtons buttons) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 594

Again, not sure what caused this but if you want, I could help you figure it out.  I'll keep the logs for a while.  I forced the deletion of the directory as the info it was dealing with isn't all that critical to me, but it might be nice to find out what happened.

Maxx

**Comment by wqweto** [comment]
This is fixed by [this PR](https://github.com/rustyx/vss2git/pull/2) on the [rustyx fork](https://github.com/rustyx/vss2git).

**Comment by VasiliPupkin256** [comment]
But rusty doesn't pull his fork to trevorr

**Comment by VasiliPupkin256** [comment]
wqweto, your fix is bad. This is a result of reckless commit combination done by vss2git. It should not combining commits if the last commit removes or overwrite a file changed by the previous commit

**Comment by wqweto** [comment]
You are right, of course. This was a quick fix to get something working.

The root cause of the issue seems to be that vss2git does not handle **folder** renames (VSS calls these "projects") very well.

**Comment by dimitar-grigorov** [comment]
Fixed this in my fork https://github.com/dimitar-grigorov/vss2git. The actual cause was that MoveFrom/MoveTo actions were processed in wrong order and stale files at the destination weren't cleaned up. Case only renames like CoolTree.cpp to cwuitree.cpp are handled with a two step workaround now too.
