### ISSUE TITLE
"no changes added to commit"

### ISSUE THREAD

**Issue by Ma-XX-oN** [trevorr/vss2git#23]
Not sure what's causing this error:

Executing: C:\Program Files\Git\cmd\git.exe add -- d:\Users\maxxon\Desktop\vss2git\Combined\4.3\CWAddIn\CWBaseAddIn.cpp
d:\Users\maxxon\Desktop\vss2git\Combined\4.4\CWAddIn\CWBaseAddIn.cpp: Edit revision 243
Executing: C:\Program Files\Git\cmd\git.exe add -- d:\Users\maxxon\Desktop\vss2git\Combined\4.4\CWAddIn\CWBaseAddIn.cpp
Committing changeset 54964 from 12/04/2002 16:18:19
Executing: C:\Program Files\Git\cmd\git.exe add -A
Generating temp file for comment: Vss2Git
Executing: C:\Program Files\Git\cmd\git.exe commit -F d:\Temp\tmpAAE1.tmp
>On branch master
>Changes not staged for commit:
>       modified:   Combined/4.4/cwmfc/Report.h
>
>no changes added to commit
ERROR: git returned exit code 1
Executable: C:\Program Files\Git\cmd\git.exe
Arguments: commit -F d:\Temp\tmpAAE1.tmp
Stdout: On branch master
Changes not staged for commit:
        modified:   Combined/4.4/cwmfc/Report.h

no changes added to commit
Stderr:
Hpdi.Vss2Git.ProcessExitException: git returned exit code 1
   at Hpdi.Vss2Git.GitWrapper.FailExitCode(String exec, String args, String stdout, String stderr, Int32 exitCode) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 301
   at Hpdi.Vss2Git.GitWrapper.ExecuteUnless(ProcessStartInfo startInfo, String unless) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 296
   at Hpdi.Vss2Git.GitWrapper.Commit(String authorName, String authorEmail, String comment, DateTime localTime) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitWrapper.cs:line 226
   at Hpdi.Vss2Git.GitExporter.<>c__DisplayClass14.<CommitChangeset>b__13() in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 569
   at Hpdi.Vss2Git.GitExporter.AbortRetryIgnore(ThreadStart work, MessageBoxButtons buttons) in d:\Users\maxxon\Documents\Visual Studio 2013\Projects\vss2git-master\vss2git-master\Vss2Git\GitExporter.cs:line 594

It looks like it's doing what it's supposed to be doing, which is adding using -A switch and then committing. I've also tried to add by specifying the specific file and tried to commit using -a and that failed too.  Not sure as yet what to do with this.

For now, I'm stuck. :(

**Comment by rustyx** [comment]
Original project isn't properly maintained. Check out [my version](https://github.com/rustyx/vss2git) it has this issue resolved.

**Comment by dimitar-grigorov** [comment]
This happens when the changeset builder groups conflicting file actions into one commit. I fixed several related issues in my fork https://github.com/dimitar-grigorov/vss2git including better conflict detection and proper staging. If you still have that VSS database you could give it a try.
